development:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_development
  pool: 5
  username: el_passatge_admin1
  password: elpassatge

test:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_test
  pool: 5
  username: el_passatge_admin1
  password: elpassatge

production:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_production
  pool: 5
  username: el_passatge_admin1
  password: elpassatge

