development:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_development
  pool: 5
  username: carper6
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_test
  pool: 5
  username: carper6
  password: 12345

production:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_production
  pool: 5
  username: carper6
  password: 12345

