development:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_development
  pool: 5
  username: Cecilia
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_test
  pool: 5
  username: Cecilia
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: el_passatge_production
  pool: 5
  username: Cecilia
  password:

